import {
  FiPlayCircle,
  FiLayout,
  FiInbox,
  FiCreditCard,
  FiUsers,
  FiCpu,
  FiClipboard,
  FiRadio,
  FiBriefcase,
  FiShoppingBag,
} from "react-icons/fi";

export const CATEGORIES = [
  { id: "getting-started", label: "Getting Started with Flowbee.io", icon: FiPlayCircle, description: "Let's help users take their first steps!" },
  { id: "dashboard", label: "Dashboard", icon: FiLayout, description: "Flowbee.io Dashboard Overview" },
  { id: "team-inbox", label: "Team Inbox", icon: FiInbox, description: "Team Inbox" },
  { id: "account-billing", label: "Account & Billing", icon: FiCreditCard, description: "Account & Billing" },
  { id: "contacts", label: "Contacts", icon: FiUsers, description: "Contacts" },
  { id: "chatbot", label: "Chatbot", icon: FiCpu, description: "Chatbot" },
  { id: "whatsapp-forms", label: "WhatsApp Forms", icon: FiClipboard, description: "WhatsApp Forms" },
  { id: "broadcast-messaging", label: "Broadcast Messaging", icon: FiRadio, description: "Broadcast Messaging" },
  { id: "agents", label: "Agents", icon: FiBriefcase, description: "Agents" },
  { id: "whatsapp-e-commerce", label: "WhatsApp E-commerce", icon: FiShoppingBag, description: "WhatsApp E-commerce" },
];

export const MODULES_DATA = {
  "getting-started": [
    { title: "Template Messages Masterclass: Understand how they work", desc: "Masterclass overview", section: "Highlight" },
    { title: "Prerequisites before you get started with Flowbee", desc: "Prerequisites", section: "Flowbee Essentials" },
    { title: "How to create and log into your Flowbee account", desc: "Account creation", section: "Flowbee Essentials" },
    { title: "How to update your WhatsApp Business profile", desc: "Profile update", section: "Flowbee Essentials" },
    { title: "How to change or update your WhatsApp display name", desc: "Display name", section: "Flowbee Essentials" },
    { title: "Guidelines for choosing your display name", desc: "Display name guidelines", section: "Flowbee Essentials" },
    { title: "How to connect your WhatsApp number to Flowbee (via Embedded Signup - Cloud API)", desc: "WhatsApp connection", section: "Flowbee Essentials" },
    { title: "Marketing Messages Lite (MM Lite): All you need to Know", desc: "MM Lite overview", section: "Flowbee Essentials" },
    { title: "Flowbee Campaigns and MM Lite", desc: "Campaigns", section: "Flowbee Essentials" },
    { title: "Migrating from On-Premise WhatsApp Business API to WhatsApp Cloud API", desc: "Migration", section: "Flowbee Essentials" },
    { title: "Onboarding with Embedded Signup: Using free number or skipping website", desc: "Embedded Signup", section: "Flowbee Essentials" },
    { title: "Introduction to Flowbee's Team Inbox", desc: "Team Inbox", section: "Flowbee Basics" },
    { title: "Understanding the new filters and navigation experience in your Flowbee Team Inbox", desc: "Filters and navigation", section: "Flowbee Basics" },
    { title: "How to add your first contact in Flowbee", desc: "Add contacts", section: "Flowbee Basics" },
    { title: "How to create your first Template Message", desc: "Create template", section: "Flowbee Basics" },
    { title: "How to send your first Campaign", desc: "Send campaign", section: "Flowbee Basics" },
    { title: "How to change the language in Flowbee", desc: "Change language", section: "Personalizing your Flowbee workspace" },
    { title: "How to change your timezone in Flowbee", desc: "Change timezone", section: "Personalizing your Flowbee workspace" },
    { title: "Managing notifications and sounds in Flowbee", desc: "Notifications", section: "Personalizing your Flowbee workspace" },
    { title: "How to configure auto replies and OOO messages", desc: "Auto replies", section: "Personalizing your Flowbee workspace" },
    { title: "How to change your Flowbee credit currency (Rate Card) from USD to INR", desc: "Credit currency", section: "Personalizing your Flowbee workspace" },
    { title: "General FAQs: Display Name", desc: "FAQ Display Name", section: "FAQs and troubleshooting" },
    { title: "General FAQs: Marketing Messages Lite (MM Lite)", desc: "FAQ MM Lite", section: "FAQs and troubleshooting" }
  ],
  "dashboard": [
    { title: "Flowbee Dashboard Overview", desc: "Understand your main dashboard metrics." },
  ],
  "team-inbox": [
    { title: "What is Team Inbox?", desc: "Overview of the team inbox feature." },
    { title: "Manage Inbox", desc: "How to manage and organize your inbox." },
    { title: "Compose Box", desc: "Using the compose box to send messages." },
    { title: "Inbox Tools & Navigation", desc: "Navigating tools within the inbox." },
    { title: "Errors & FAQ", desc: "Common errors and frequently asked questions." },
  ],
  "account-billing": [
    { title: "Chat History Retention Policy", desc: "Learn about our data retention policies." },
  ],
  "contacts": [
    { title: "Introduction", desc: "Introduction to contacts." },
    { title: "Add Contact", desc: "How to add a new contact." },
    { title: "Contact Groups", desc: "Organizing contacts into groups." },
    { title: "Contact Management", desc: "Managing your contact lists." },
  ],
  "chatbot": [
    { title: "Introduction", desc: "Introduction to chatbots." },
    { title: "Chatbot Interface", desc: "Navigating the chatbot interface." },
    { title: "Chatbot Nodes", desc: "Understanding chatbot nodes." },
    { title: "Set Up Default Bot", desc: "Setting up your default bot." },
    { title: "Keyword Trigger Setup", desc: "Setting up triggers for keywords." },
    { title: "Session Timeout & Manual Chat Expiry", desc: "Handling chat sessions." },
  ],
  "whatsapp-forms": [
    { title: "Introduction", desc: "Introduction to WhatsApp forms." },
    { title: "Form Capabilities", desc: "What you can do with WhatsApp forms." },
  ],
  "broadcast-messaging": [
    { title: "Introduction", desc: "Introduction to broadcast messaging." },
    { title: "WhatsApp Messaging Limits & Tiers", desc: "Understanding messaging limits." },
    { title: "WhatsApp Templates", desc: "Using templates for WhatsApp." },
    { title: "Create Template – Support & Approval", desc: "Creating and getting templates approved." },
    { title: "Broadcast Overview & Analytics", desc: "Analyzing your broadcasts." },
    { title: "Send Broadcast Campaign", desc: "How to send a broadcast campaign." },
  ],
  "agents": [
    { title: "Agents", desc: "Managing your agents." },
  ],
  "whatsapp-e-commerce": [
    { title: "WhatsApp E-commerce", desc: "Introduction to WhatsApp E-commerce." },
    { title: "Connect WhatsApp Catalog", desc: "Connecting your product catalog." },
    { title: "Product Management", desc: "Managing your products." },
    { title: "Product Category Management", desc: "Managing product categories." },
    { title: "Order Dashboard (WhatsApp Commerce)", desc: "Viewing your orders." },
    { title: "E-commerce Automation", desc: "Automating your e-commerce workflows." },
    { title: "External E-commerce Store", desc: "Connecting external stores." },
  ],
};
